package com.cleancode.ecommerce.user;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.cleancode.ecommerce.shared.kernel.Email;
import com.cleancode.ecommerce.shared.kernel.Password;
import com.cleancode.ecommerce.user.domain.User;
import com.cleancode.ecommerce.user.domain.UserId;

class UserTest {

    private Email validEmail;
    private Password validPassword;

    // Minimal concrete subclass to allow testing abstract User behaviors
    private static class TestUser extends User {
        TestUser(Email email, Password password) {
            super(email, password);
        }

        TestUser(UserId userId, Email email, Password password) {
            super(userId, email, password);
        }
    }

    @BeforeEach
    void setUp() {
        validEmail = new Email("clean@code.com");
        validPassword = new Password("Secure123!");
    }

    @Test
    @DisplayName("Should initialize User with a generated UserId when using the brief constructor")
    void shouldInitializeWithAutoGeneratedId() {
        User user = new TestUser(validEmail, validPassword);

        assertThat(user.getUserId()).isNotNull().isNotEmpty();
        assertThat(user.getEmail()).isEqualTo("clean@code.com");
        assertThat(user.getPassword()).isEqualTo("Secure123!");
    }

    @Test
    @DisplayName("Should initialize User with the explicit UserId when provided")
    void shouldInitializeWithExplicitId() {
        UserId customId = new UserId("custom-id-123");
        
        User user = new TestUser(customId, validEmail, validPassword);

        assertThat(user.getUserId()).isEqualTo("custom-id-123");
    }

    @Test
    @DisplayName("Should throw NullPointerException if required constructor arguments are null")
    void shouldThrowExceptionOnNullArguments() {
        UserId id = new UserId();

        // Testing short constructor guards
        assertThatThrownBy(() -> new TestUser(null, validPassword)).isInstanceOf(NullPointerException.class);
        assertThatThrownBy(() -> new TestUser(validEmail, null)).isInstanceOf(NullPointerException.class);

        // Testing full constructor guards
        assertThatThrownBy(() -> new TestUser(null, validEmail, validPassword)).isInstanceOf(NullPointerException.class);
        assertThatThrownBy(() -> new TestUser(id, null, validPassword)).isInstanceOf(NullPointerException.class);
        assertThatThrownBy(() -> new TestUser(id, validEmail, null)).isInstanceOf(NullPointerException.class);
    }

    @Test
    @DisplayName("Should update password state when a valid cleartext string matches validation rules")
    void shouldUpdatePasswordSuccessfully() {
        User user = new TestUser(validEmail, validPassword);
        String updatedRawPassword = "NewSecure456#";

        user.updatePassword(updatedRawPassword);

        assertThat(user.getPassword()).isEqualTo(updatedRawPassword);
    }

    @Test
    @DisplayName("Should throw exception when updatePassword receives a value violating Password constraints")
    void shouldFailPasswordUpdateOnInvalidFormat() {
        User user = new TestUser(validEmail, validPassword);
        
        // This fails inside the internal new Password() initialization due to missing uppercase/special
        assertThatThrownBy(() -> user.updatePassword("weak"))
                .isInstanceOf(RuntimeException.class); 
    }

    @Test
    @DisplayName("Should ensure equality (equals and hashCode) is strictly tied to the UserId attribute")
    void shouldRespectEqualsAndHashCodeContractBasedOnUserId() {
        UserId sharedId = new UserId("user-id-555");
        Email secondaryEmail = new Email("other@code.com");
        Password secondaryPassword = new Password("Different987$");

        // Two users with different fields but identical IDs must be equal
        User user1 = new TestUser(sharedId, validEmail, validPassword);
        User user2 = new TestUser(sharedId, secondaryEmail, secondaryPassword);
        
        User userWithDifferentId = new TestUser(new UserId("other-id"), validEmail, validPassword);

        // Equals validations
        assertThat(user1).isEqualTo(user2);
        assertThat(user1).isNotEqualTo(userWithDifferentId);
        assertThat(user1).isNotEqualTo(null);

        // HashCode validations
        assertThat(user1.hashCode()).isEqualTo(user2.hashCode());
        assertThat(user1.hashCode()).isNotEqualTo(userWithDifferentId.hashCode());
    }
}